"""initial

Revision ID: e5838d1ce582
Revises: 
Create Date: 2026-05-21 15:09:36.819914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5838d1ce582'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asteroids',
    sa.Column('asteroid_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('estimated_diameter', sa.Float(), nullable=True),
    sa.Column('absolute_magnitude_h', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('asteroid_id')
    )
    op.create_index(op.f('ix_asteroids_name'), 'asteroids', ['name'], unique=True)
    op.create_table('impact_events',
    sa.Column('impact_event_id', sa.String(), nullable=False),
    sa.Column('asteroid_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('impact_probability', sa.Float(), nullable=False),
    sa.Column('energy', sa.Float(), nullable=False),
    sa.Column('dangerous', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['asteroid_id'], ['asteroids.asteroid_id'], ),
    sa.PrimaryKeyConstraint('impact_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact_events')
    op.drop_index(op.f('ix_asteroids_name'), table_name='asteroids')
    op.drop_table('asteroids')
    # ### end Alembic commands ###
