"""add exoplanets table

Revision ID: 125d235888c0
Revises: 835dcb05d3ce
Create Date: 2026-07-21 20:42:12.066661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125d235888c0'
down_revision: Union[str, Sequence[str], None] = '835dcb05d3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exoplanets',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('host_name', sa.String(), nullable=False),
    sa.Column('discovery_year', sa.Integer(), nullable=False),
    sa.Column('discovery_method', sa.String(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('mass', sa.Float(), nullable=False),
    sa.Column('density', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('insolation', sa.Float(), nullable=False),
    sa.Column('orbit_period', sa.Float(), nullable=False),
    sa.Column('orbit_eccentricity', sa.Float(), nullable=False),
    sa.Column('orbit_smax', sa.Float(), nullable=False),
    sa.Column('star_temperature', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exoplanets')
    # ### end Alembic commands ###
