"""add index on impact_events.asteroid_id

Revision ID: 835dcb05d3ce
Revises: a1b2c3d4e5f6
Create Date: 2026-07-02 12:13:35.529130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835dcb05d3ce'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_index('ix_impact_events_asteroid_id', 'impact_events', ['asteroid_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_impact_events_asteroid_id', table_name='impact_events')
    # ### end Alembic commands ###
