name: Populate Asteroids Database

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  populate-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: ./backend
        run: poetry install --no-root

      - name: Run populate script
        working-directory: ./backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          NASA_JPL_SENTRY_BASE_URL: ${{ secrets.NASA_JPL_SENTRY_BASE_URL }}
          NASA_JPL_SBDB_BASE_URL: ${{ secrets.NASA_JPL_SBDB_BASE_URL }}
          NASA_NEO_WS_BASE_URL: ${{ secrets.NASA_NEO_WS_BASE_URL }}
        run: poetry run python -m script.populate_asteroids_database
